<a href="https://colab.research.google.com/github/yoloaryan/Pandas/blob/main/Py(pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

In [2]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
!pip install --upgrade pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 4.3 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 93.7 MB/s eta 0:00:00
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.3 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.3 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.3 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.3 which is incompatible.
Successfully installed pandas-3.0.3

In [4]:
labels =['a','b','c']
my_list =[10,20,30]
arr= np.array([10,20,30])
d= {1:10,2:20,3:30}

In [5]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [7]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [9]:
data ={
    'Name':['John','Anna','Peter','Linda'],
    'Age': [28,34,39,42],
    'City':['New York','Paris','Berlin','London'],
    'Salary':[65000,70000,62000,85000]
}
df= pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   39    Berlin   62000
3  Linda   42    London   85000

In [10]:
data_list = [
  ['John',28,'New York',65000],
	['Anna',34,'Paris',70000],
	['Peter',39,'Berlin',62000],
	['Linda',42,'London',85000]

]
df2= pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=columns)

In [11]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   39    Berlin   62000
3  Linda   42    London   85000

# Selection and indexing of columns

In [12]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   39    Berlin   62000
3  Linda   42    London   85000

In [13]:
df2[0]
#--> throws an error because when we use dataframe ,columns anme came in

KeyError: 0

In [14]:
df2['Age']

0    28
1    34
2    39
3    42
Name: Age, dtype: int64

In [15]:
df2['Salary']

0    65000
1    70000
2    62000
3    85000
Name: Salary, dtype: int64

In [16]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

Creating a new columns

In [17]:
df2["Designition"] = ["Doctor","Eng.","Doctor","Eng."]

In [18]:
df2

    Name  Age      City  Salary Designition
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   39    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

Removing columns

In [19]:
df2.drop('Designition',axis = 1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   39    Berlin   62000
3  Linda   42    London   85000

In [20]:
df2

    Name  Age      City  Salary Designition
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   39    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [21]:
df2.drop('Designition',axis=1,inplace= True)

In [22]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   39    Berlin   62000
3  Linda   42    London   85000

In [23]:
df2.drop(["City","Salary"],axis=1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   39
3  Linda   42

In [24]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   39    Berlin   62000
3  Linda   42    London   85000

In [25]:
df2.drop(["City","Salary"],axis =1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   39
3  Linda   42

In [26]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   39    Berlin   62000
3  Linda   42    London   85000

In [27]:
df2.drop(0,axis = 0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   39  Berlin   62000
3  Linda   42  London   85000

# Selecting Rows

In [28]:
df2[0]

KeyError: 0

In [29]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [30]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [31]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

**Selecting subsets of rows and columns**


---

In [32]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   39    Berlin   62000
3  Linda   42    London   85000

In [34]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [38]:
df.loc[[2,3],["Name","Age"]]

    Name  Age
2  Peter   39
3  Linda   42

In [37]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   39    Berlin   62000
3  Linda   42    London   85000

## Conditional Selection

In [41]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   39    Berlin   62000
3  Linda   42    London   85000

In [40]:
#only want to see those people whose age is above 30

In [42]:
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   39  Berlin   62000
3  Linda   42  London   85000

In [47]:
#df2[if["Age"]>30] # in pandas this is wrong

In [44]:
#i only want people whose age is above 30 and their city must be in paris

In [46]:
df2[(df2["Age"] > 30) & (df2["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000